version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    command: npm run dev
    ports:
      - '4001:7000'
    restart: always
    volumes:
      - ./front:/app
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - '4002:8000'
    restart: always
    volumes:
      - ./api:/var/www/html
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_db
      DB_PASSWORD: 1234
    networks:
      - mynetwork

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '4003:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_db
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: 172.20.0.4
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
